### ISSUE TITLE
Bot didn't catch code signing issue

### ISSUE THREAD

**Issue by getaaron** [fastlane/issue-bot#42]
https://github.com/fastlane/fastlane/issues/9401 should've generated the automatic code signing guide suggestion.

**Comment by revolter** [comment]
Testing with the current version of the bot against the exact same message [correctly detects the code signing issue](https://github.com/revolter/fastlane-bot-test/issues/3). Maybe it was a problem with the server it's running on, and this being so old, I think we may close it until it happens again (more so if it happens multiple times).

**Comment by KrauseFx** [comment]
Yeah, might have been a server issue, let's close this, thanks @revolter for testing this with the latest version
